name: Test Pre Commit

on:
  pull_request:
    branches:
      - 15.0

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          pip install pre-commit
          pre-commit run -a
